# Generated by Django 5.1.3 on 2024-12-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OlchovBirligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olchov_birligi', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "O'lchov Birlig",
                'verbose_name_plural': "O'lchov Birliglar",
            },
        ),
        migrations.CreateModel(
            name='KirdiChiqdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('amaliyot_turi', models.CharField(choices=[('Kirdi', 'Kirdi'), ('Chiqdi', 'Chiqdi')], max_length=15)),
                ('mahsulot_nomi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ombor.mahsulot')),
            ],
            options={
                'verbose_name': 'Kirdi Chiqdi',
                'verbose_name_plural': 'Kirdi Chiqdi',
            },
        ),
        migrations.CreateModel(
            name='MahsulotBalans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoldiq', models.PositiveIntegerField(default=0)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ombor.mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot Joriy Balansi',
                'verbose_name_plural': 'Mahsulot Joriy Balansi',
            },
        ),
        migrations.CreateModel(
            name='MahsulotBalansTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField()),
                ('qoldiq', models.PositiveIntegerField()),
                ('sana', models.DateTimeField()),
                ('amaliyot_turi', models.CharField(max_length=5)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ombor.mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot Balans Tarixi',
                'verbose_name_plural': 'Mahsulot Balans Tarixi',
            },
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='olchov_birligi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ombor.olchovbirligi'),
        ),
    ]
