# Generated by Django 5.1.3 on 2024-11-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OlchovBirligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olchov_birligi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotBalansTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField()),
                ('qoldiq', models.PositiveIntegerField()),
                ('sana', models.DateTimeField()),
                ('amaliyot_turi', models.CharField(max_length=5)),
                ('mahsulot_nomi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.mahsulot')),
                ('olchov_birligi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.olchovbirligi')),
            ],
        ),
        migrations.CreateModel(
            name='MahsulotBalans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoldiq', models.PositiveIntegerField(default=0)),
                ('mahsulot_nomi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.mahsulot')),
                ('olchov_birligi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.olchovbirligi')),
            ],
        ),
        migrations.CreateModel(
            name='KirdiChiqdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('amaliyot_turi', models.CharField(choices=[('Kirdi', 'Kirdi'), ('Chiqdi', 'Chiqdi')], max_length=15)),
                ('mahsulot_nomi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.mahsulot')),
                ('olchov_birligi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ombor.olchovbirligi')),
            ],
        ),
    ]
