# Generated by Django 5.1.3 on 2024-12-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='olchov_birligi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ombor.olchovbirligi'),
        ),
    ]
